### ISSUE TITLE
TypeScript 데이터 다루는데 이슈

### ISSUE THREAD

**Issue by sphy1597** [wanted-7h/hotplace#35]
Api에서 호출된 값을 Text로 변환해서 출력하면 정상적으로 데이터가 나오는데 
-  const data = await response.text()
값을 사용하려고 하면 data가 unknown타입이라고 나오면서 사용할 수 없습니다...

**Comment by scarf005** [comment]
오류가 발생하는 소스 코드와 에러 메시지를 같이 올려주셔야 원인 분석이 가능할 것 같아요!

**Comment by sphy1597** [comment]
export const dbScheduler = async() => {

    console.log(new Date() + "Running Scheduler !!! ")


    const key = process.env.api_key

    //업태명 코드(업종명)
    const SANITTN_BIZCOND_NM = "chifood"
    const url = "https://openapi.gg.go.kr/Genrestrt"+ SANITTN_BIZCOND_NM +"?key="+key+"&type=json&pSize=5&pindex=1"

    try {
        const response = await fetch(url, { method: "GET" });

        if (response.ok) {
            const data = await response.json();

            // 원하는 데이터 필드에 접근해서 출력
            const desiredValue = data.Genrestrtchifood;  >> 이부분에서 data는 unkniwn형식이라고 나오는 상태입니다
            console.log("Desired Value: ", desiredValue);
        } else {
            console.error("Response not ok:", response.status);
        }
    } catch (error) {
        console.error("Error fetching data: ", error);
    }

  };

**Comment by scarf005** [comment]
- [코드 블록과 문법 하이라이트 사용하기](https://docs.github.com/ko/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)도 참고해주세요~

**Comment by sphy1597** [comment]
axios 패키지로 Req, Res를 다루기 쉽게 바꾸고
interface를 추가해서 Response에 대한 값들의 타입을 정의해서 unknown타입이 되지 않게 해주었습니다
```
import axios from 'axios';

export const dbScheduler = async() => {

    console.log(new Date() + "Running Scheduler !!! ")


    const key = process.env.api_key

    //업태명 코드(업종명)
    const SANITTN_BIZCOND_NM = "chifood"
    const url = "https://openapi.gg.go.kr/Genrestrt"+ SANITTN_BIZCOND_NM +"?key="+key+"&type=json&pSize=5&pindex=1"
   
    try{
        
        const response = await axios.get(url);
        const responseData : RestaurantResponse = response.data;
        console.log(response.data);

        //[0] = head / [1] = row 
        const restaurants : Restaurant[] = responseData.Genrestrtchifood[1].row;

        console.log('가게 목록', restaurants);

    }catch(error){
        console.log("api 호출 중 오류 발생 : ", error)
    }
    
  };

interface Restaurant {
    SIGUN_NM: string;
    BIZPLC_NM: string;
    LICENSG_DE: string;
    BSN_STATE_NM: string;
    SANITTN_BIZCOND_NM: string;
    REFINE_LOTNO_ADDR: string;
    REFINE_ROADNM_ADDR: string;
    REFINE_ZIP_CD: string;
    REFINE_WGS84_LOGT: string;
    REFINE_WGS84_LAT: string;
}


interface RestaurantResponse {
    Genrestrtchifood: {
        head: {
            list_total_count: number;
            RESULT: {
                CODE: string;
                MESSAGE: string;
            };
            api_version: string;
        }[];
        row: Restaurant[];
    }[];
}


```
- 추가로 head와 row가 Genrestrtchifood[0]에 한번에 들어가는 줄 알았는데 Genrestrtchifood[1]에 로우가 있었습니다...

**Comment by scarf005** [comment]
문제가 해결된 것 같아 닫도록 하겠습니다!
