### ISSUE TITLE
시퀄라이즈 Class constructor Model 이슈

### ISSUE THREAD

**Issue by Yonge2** [wanted-7h/hotplace#36]
시퀄라이즈 모델 정의 시, 공식문서 참고하여 클래스를 사용하였습니다.

초기설정 시, tsconfig 의 컴파일러 옵션 중 target을 es5로 했었는데,

es5에서는 class를 지원하지 않아 target을 es6로 변경했습니다!

**Comment by scarf005** [comment]
혹시 어떤 이슈가 있었는지, 해결되었다면 어떤 방식을 사용하셨는지도 알려주시면 좋을 것 같아요!
