### ISSUE TITLE
회원 가입 후 로그인 불가

### ISSUE THREAD

**Issue by scarf005** [wanted-7h/hotplace#76]
### 문제 재현

1. [회원가입](http://localhost:3000/openapi/#/user/post_users)
2. [로그인](http://localhost:3000/openapi/#/user/post_users)

```
POST /users/login 200 14.222 ms - 365
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[ErrorReply: ERR value is not an integer or out of range]

Node.js v20.9.0
Failed running './src/app.ts'


```

**Comment by Yonge2** [comment]
방금 main 브랜치 pull 해서 
postman 으로 테스트 진행해봤는데 제 환경에서는 잘 됩니다 ㅠ

에러 원인을 찾아보고 싶은데, 입력 케이스 알려주시면 감사하겠습니다!
