### ISSUE TITLE
#78 Pr 이후 zod error 발생

### ISSUE THREAD

**Issue by sphy1597** [wanted-7h/hotplace#79]
지금 수업이 시작돼서 에러 메세지는 조금 후에 첨부하겠습니다. 
메인 풀 이후 npm i 진행했고 npm run dev로 실행했습니다

혹시 .env 파일 또는 패키지 변화에 따른 코드 변경해야 하는 부분이 있을까요?

**Comment by scarf005** [comment]
환경 변수 이름이 `api_key` -> `API_KEY`로 변경되었는데 그로 인해 발생한 것 같습니다.

**Comment by sphy1597** [comment]
넵 확인해 보겠습니다
